# Generated by Django 3.1.3 on 2020-11-19 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nearbyshops', '0002_auto_20201119_1927'),
    ]

    operations = [
    ]
